-- 코드를 작성해주세요
WITH PARENT_INFO AS
(SELECT PARENT_ID, COUNT(*) 'CNT' FROM ECOLI_DATA GROUP BY PARENT_ID)
SELECT E.ID, IFNULL((SELECT CNT FROM PARENT_INFO P WHERE P.PARENT_ID = E.ID), 0) 'CHILD_COUNT'
FROM ECOLI_DATA E
ORDER BY E.ID;