-- 코드를 작성해주세요
SELECT P.ID, 
CASE
    WHEN(SELECT COUNT(*) FROM ECOLI_DATA C WHERE C.SIZE_OF_COLONY >= P.SIZE_OF_COLONY)/(SELECT COUNT(*) FROM ECOLI_DATA) <= 0.25
    THEN 'CRITICAL'
    WHEN(SELECT COUNT(*) FROM ECOLI_DATA C1 WHERE C1.SIZE_OF_COLONY >= P.SIZE_OF_COLONY)/(SELECT COUNT(*) FROM ECOLI_DATA) <= 0.5
    THEN 'HIGH'
    WHEN(SELECT COUNT(*) FROM ECOLI_DATA C2 WHERE C2.SIZE_OF_COLONY >= P.SIZE_OF_COLONY)/(SELECT COUNT(*) FROM ECOLI_DATA) <= 0.75
    THEN 'MEDIUM'
    WHEN(SELECT COUNT(*) FROM ECOLI_DATA C3 WHERE C3.SIZE_OF_COLONY >= P.SIZE_OF_COLONY)/(SELECT COUNT(*) FROM ECOLI_DATA) <= 1
    THEN 'LOW'
END "COLONY_NAME"
FROM ECOLI_DATA P
ORDER BY ID ASC;

# SELECT P.ID, 
# CASE
#     WHEN 1/2 <= 0.25
#     THEN 'CRITICAL'
#     WHEN 1/2 <= 0.5
#     THEN 'HIGH'
#     WHEN 1/2 <= 0.75
#     THEN 'MEDIUM'
#     WHEN 1/2 <= 1
#     THEN 'LOW'
# END "COLONY_NAME"
# FROM ECOLI_DATA P
# ORDER BY SIZE_OF_COLONY DESC;

