-- 코드를 작성해주세요
SELECT CONCAT(IF(MONTH(E.DIFFERENTIATION_DATE)>=1 AND MONTH(E.DIFFERENTIATION_DATE)<=3, 1, IF(MONTH(E.DIFFERENTIATION_DATE)>=4 AND MONTH(E.DIFFERENTIATION_DATE)<=6, 2,IF(MONTH(E.DIFFERENTIATION_DATE)>=7 AND MONTH(E.DIFFERENTIATION_DATE)<=9, 3, 4))), "Q") "QUARTER", COUNT(*) "ECOLI_COUNT"
FROM ECOLI_DATA e
GROUP BY QUARTER
ORDER BY QUARTER;