-- 코드를 작성해주세요
SELECT J.ID, J.GENOTYPE, J.PARENT_GENOTYPE
FROM 
(
    SELECT P.ID, P.PARENT_ID, P.GENOTYPE, C.GENOTYPE "PARENT_GENOTYPE"
    FROM ECOLI_DATA P 
    LEFT OUTER JOIN ECOLI_DATA C
    ON P.PARENT_ID = C.ID
) J
WHERE J.GENOTYPE & J.PARENT_GENOTYPE = J.PARENT_GENOTYPE
ORDER BY J.ID;