-- 코드를 작성해주세요
SELECT YEAR(E.DIFFERENTIATION_DATE) "YEAR", 
((SELECT MAX(S.SIZE_OF_COLONY) FROM ECOLI_DATA S WHERE YEAR(S.DIFFERENTIATION_DATE) = YEAR(E.DIFFERENTIATION_DATE)) - E.SIZE_OF_COLONY) "YEAR_DEV",
ID
FROM ECOLI_DATA E
ORDER BY YEAR, YEAR_DEV;